version: '3.8'

services:
  db:
    image: postgres:16
    container_name: fluxivamed-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fluxivamed
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - fluxivamed-net

  backend:
    image: eclipse-temurin:21-jre
    container_name: fluxivamed-backend
    depends_on:
      - db
    working_dir: /app
    # ATENÇÃO: ajuste o nome do jar conforme o gerado no target/
    # (ex.: fluxivamed-backend-0.0.1-SNAPSHOT.jar → app.jar dentro do container)
    volumes:
        - ./target/app.jar:/app/app.jar:ro
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/fluxivamed
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SECURITY_JWT_SECRET: F2WnythSO73qDCvHKFpljVzvGNFQdD8kNnXYcuzDox1C67y0D644bq6bPreHwe1z2HGY7WmNYC112EyCOVx2+A==
    command: ["java","-jar","/app/app.jar"]
    ports:
      - "8080:8080"
    networks:
      - fluxivamed-net
    restart: unless-stopped

volumes:
  pgdata:

networks:
  fluxivamed-net: